name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Configure CMake
      run: cd task-ci
        
    - name: Build 
      run: |
        cd task-ci
        mkdir 3rdparty
        cd 3rdparty
        git clone https://github.com/google/googletest.git .
        cd ..
        mkdir build
        cd build 
        cmake ..
        make
        cd ..
        cd bin
        ./C
        ./CTestExe
        
    - name: Test
      uses: akhtyamovpavel/ActionGtestReport@v0.0.9
      with: 
        exec-path: bin/CTestExe
        working-directory: task-ci
        report-path: test-report/report.xml
        
